#pragma once

///////////////// This file was generated by Mathematica. //////////////////

#include "EVADE/Utilities/Polynomial.hpp"
#include <string>
#include <vector>

namespace EVADE {
namespace Models {

class THDMSZ3 {
//////////////////////// Static member functions ///////////////////////////
public:
  static const std::vector<std::string> &FieldNames();

  static const std::vector<std::string> &ParameterNames();

  static Utilities::Polynomial VPoly(const std::vector<double> &parameters);

  static Utilities::Polynomial VPoly4(const std::vector<double> &parameters);

  static double V(const std::vector<double> &parameters,
	                const std::vector<double> &fields);

  static double V4(const std::vector<double> &parameters,
	                 const std::vector<double> &fields);

  static std::vector<double> InitialVacuum(const std::vector<double> &parameters);

////////////////////// Non-Static member functions ////////////////////////
public:
  explicit THDMSZ3(const std::vector<double> &parameters);
  explicit THDMSZ3(std::vector<double> &&parameters);

  double Msq(const std::vector<double> &direction) const;

  double A(const std::vector<double> &direction) const;

  double Lam(const std::vector<double> &direction) const;

private:
	std::vector<double> p_;

};
} // namespace Models
} // namespace EVADE
