! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 6/30/2025 , 10:25:26
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 3.0.0
! Model name: hdms_sarah2
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 150
! --------------------------------------------------------------------------------
! 
! --------------------------------------------------------------------------------

module parameters_hdms_sarah2_local
use parameters_hdms_sarah2_global
implicit none
public
save

real(kind=default) :: vS, ZH11, ZH12, ZH13, ZH21, ZH22, ZH23, ZH31, ZH32, ZH33,  &
   ZA11, ZA12, ZA13, ZA21, ZA22, ZA23, ZA31, ZA32, ZA33, betaH, aS, aEWinv, Gf, g3,  &
   ZP11, ZP12, ZP21, ZP22, ee, TW, g1, g2, v, vd, vu
complex(kind=default) :: MUS1, MU11, MU12, MU21, MU22, MUS2, Lam1pp, Lam4p,  &
   Lam6p, Lam7p, Lam5p, Lam2pp, Lam6, Lam5, Lam7, Lam3p, Lam1, Lam4, Lam3, Lam2, Lam1p,  &
   Lam2p, Lam3pp, Yu11, Yu12, Yu13, Yu21, Yu22, Yu23, Yu31, Yu32, Yu33, epsU11, epsU12,  &
   epsU13, epsU21, epsU22, epsU23, epsU31, epsU32, epsU33, Yd11, Yd12, Yd13, Yd21, Yd22,  &
   Yd23, Yd31, Yd32, Yd33, Ye11, Ye12, Ye13, Ye21, Ye22, Ye23, Ye31, Ye32, Ye33, epsD11 &
   , epsD12, epsD13, epsD21, epsD22, epsD23, epsD31, epsD32, epsD33, epsE11, epsE12,  &
   epsE13, epsE21, epsE22, epsE23, epsE31, epsE32, epsE33, ZDL11, ZDL12, ZDL13, ZDL21,  &
   ZDL22, ZDL23, ZDL31, ZDL32, ZDL33, ZDR11, ZDR12, ZDR13, ZDR21, ZDR22, ZDR23, ZDR31,  &
   ZDR32, ZDR33, ZUL11, ZUL12, ZUL13, ZUL21, ZUL22, ZUL23, ZUL31, ZUL32, ZUL33, ZUR11,  &
   ZUR12, ZUR13, ZUR21, ZUR22, ZUR23, ZUR31, ZUR32, ZUR33, ZEL11, ZEL12, ZEL13, ZEL21,  &
   ZEL22, ZEL23, ZEL31, ZEL32, ZEL33, ZER11, ZER12, ZER13, ZER21, ZER22, ZER23, ZER31,  &
   ZER32, ZER33

end module parameters_hdms_sarah2_local