! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 6/30/2025 , 10:25:26
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 3.0.0
! Model name: hdms_sarah2
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 150
! --------------------------------------------------------------------------------
! 
! --------------------------------------------------------------------------------

module parameters_hdms_sarah2_global
use kinds
use constants, only: pi
implicit none
public
private :: sec_re, sec_cmplx, csc_re, csc_cmplx
save

real(kind=default), parameter :: fr_zero=0.
! masses and widths:
real(kind=default) :: Md1, Md2, Md3, Mu1, Mu2, Mu3, Me1, Me2, Me3, Mh1, Mh2, Mh3 &
   , MAh2, MAh3, MHm2, MZ, MWm, Wu3, Wh1, Wh2, Wh3, WAh2, WAh3, WHm2, WZ, WWm
! vertex factors:
complex(kind=default) :: G_ah2_ah2_ah2, G_ah2_ah2_ah3, G_ah2_ah3_ah3,  &
   G_ah3_ah3_ah3, G_ah2_ah2_h1, G_ah2_ah2_h2, G_ah2_ah2_h3, G_ah2_ah3_h1, G_ah2_ah3_h2,  &
   G_ah2_ah3_h3, G_ah3_ah3_h1, G_ah3_ah3_h2, G_ah3_ah3_h3, G_ah2_h1_h1, G_ah2_h1_h2,  &
   G_ah2_h1_h3, G_ah2_h2_h2, G_ah2_h2_h3, G_ah2_h3_h3, G_ah3_h1_h1, G_ah3_h1_h2, G_ah3_h1_h3,  &
   G_ah3_h2_h2, G_ah3_h2_h3, G_ah3_h3_h3, G_ah2_hm2_hm2c, G_ah3_hm2_hm2c, G_h1_h1_h1,  &
   G_h1_h1_h2, G_h1_h1_h3, G_h1_h2_h2, G_h1_h2_h3, G_h1_h3_h3, G_h2_h2_h2, G_h2_h2_h3,  &
   G_h2_h3_h3, G_h3_h3_h3, G_h1_hm2_hm2c, G_h2_hm2_hm2c, G_h3_hm2_hm2c, G_ah2_ah2_wmc_wm_1,  &
   G_ah2_ah3_wmc_wm_1, G_ah3_ah3_wmc_wm_1, G_ah2_ah2_z_1_z_1, G_ah2_ah3_z_1_z_1, G_ah3_ah3_z_1_z_1,  &
   G_ah2_hm2_wmc_a_1, G_ah3_hm2_wmc_a_1, G_ah2_hm2_wmc_z_1, G_ah3_hm2_wmc_z_1, G_ah2_hm2c_a_1_wm_1,  &
   G_ah3_hm2c_a_1_wm_1, G_ah2_hm2c_wm_1_z_1, G_ah3_hm2c_wm_1_z_1, G_h1_h1_wmc_wm_1, G_h1_h2_wmc_wm_1,  &
   G_h1_h3_wmc_wm_1, G_h2_h2_wmc_wm_1, G_h2_h3_wmc_wm_1, G_h3_h3_wmc_wm_1, G_h1_h1_z_1_z_1,  &
   G_h1_h2_z_1_z_1, G_h1_h3_z_1_z_1, G_h2_h2_z_1_z_1, G_h2_h3_z_1_z_1, G_h3_h3_z_1_z_1,  &
   G_h1_hm2_wmc_a_1, G_h2_hm2_wmc_a_1, G_h3_hm2_wmc_a_1, G_h1_hm2_wmc_z_1, G_h2_hm2_wmc_z_1,  &
   G_h3_hm2_wmc_z_1, G_hm2_hm2c_a_1_a_1, G_hm2_hm2c_a_1_z_1, G_hm2_hm2c_wmc_wm_1,  &
   G_hm2_hm2c_z_1_z_1, G_z_1_ah2_h1, G_z_1_ah2_h2, G_z_1_ah2_h3, G_z_1_ah3_h1, G_z_1_ah3_h2,  &
   G_z_1_ah3_h3, G_wmc_ah2_hm2, G_wmc_ah3_hm2, G_wmc_h1_hm2, G_wmc_h2_hm2, G_wmc_h3_hm2,  &
   G_wm_1_h1_hm2c, G_wm_1_h2_hm2c, G_wm_1_h3_hm2c, G_a_1_hm2_hm2c, G_z_1_hm2_hm2c, G_h1_wmc_wm_1 &
   , G_h2_wmc_wm_1, G_h3_wmc_wm_1, G_h1_z_1_z_1, G_h2_z_1_z_1, G_h3_z_1_z_1,  &
   G_hm2_wmc_a_1, G_hm2_wmc_z_1, G_d1bar_ah2_d1(2), G_d1bar_ah3_d1(2), G_d1bar_ah2_d2(2),  &
   G_d1bar_ah3_d2(2), G_d1bar_ah2_d3(2), G_d1bar_ah3_d3(2), G_d2bar_ah2_d1(2), G_d2bar_ah3_d1(2 &
   ), G_d2bar_ah2_d2(2), G_d2bar_ah3_d2(2), G_d2bar_ah2_d3(2), G_d2bar_ah3_d3(2),  &
   G_d3bar_ah2_d1(2), G_d3bar_ah3_d1(2), G_d3bar_ah2_d2(2), G_d3bar_ah3_d2(2), G_d3bar_ah2_d3(2 &
   ), G_d3bar_ah3_d3(2), G_e1bar_ah2_e1(2), G_e1bar_ah3_e1(2), G_e1bar_ah2_e2(2),  &
   G_e1bar_ah3_e2(2), G_e1bar_ah2_e3(2), G_e1bar_ah3_e3(2), G_e2bar_ah2_e1(2), G_e2bar_ah3_e1(2 &
   ), G_e2bar_ah2_e2(2), G_e2bar_ah3_e2(2), G_e2bar_ah2_e3(2), G_e2bar_ah3_e3(2),  &
   G_e3bar_ah2_e1(2), G_e3bar_ah3_e1(2), G_e3bar_ah2_e2(2), G_e3bar_ah3_e2(2), G_e3bar_ah2_e3(2 &
   ), G_e3bar_ah3_e3(2), G_u1bar_ah2_u1(2), G_u1bar_ah3_u1(2), G_u1bar_ah2_u2(2),  &
   G_u1bar_ah3_u2(2), G_u1bar_ah2_u3(2), G_u1bar_ah3_u3(2), G_u2bar_ah2_u1(2), G_u2bar_ah3_u1(2 &
   ), G_u2bar_ah2_u2(2), G_u2bar_ah3_u2(2), G_u2bar_ah2_u3(2), G_u2bar_ah3_u3(2),  &
   G_u3bar_ah2_u1(2), G_u3bar_ah3_u1(2), G_u3bar_ah2_u2(2), G_u3bar_ah3_u2(2), G_u3bar_ah2_u3(2 &
   ), G_u3bar_ah3_u3(2), G_d1bar_h1_d1(2), G_d1bar_h2_d1(2), G_d1bar_h3_d1(2),  &
   G_d1bar_h1_d2(2), G_d1bar_h2_d2(2), G_d1bar_h3_d2(2), G_d1bar_h1_d3(2), G_d1bar_h2_d3(2),  &
   G_d1bar_h3_d3(2), G_d2bar_h1_d1(2), G_d2bar_h2_d1(2), G_d2bar_h3_d1(2), G_d2bar_h1_d2(2),  &
   G_d2bar_h2_d2(2), G_d2bar_h3_d2(2), G_d2bar_h1_d3(2), G_d2bar_h2_d3(2), G_d2bar_h3_d3(2),  &
   G_d3bar_h1_d1(2), G_d3bar_h2_d1(2), G_d3bar_h3_d1(2), G_d3bar_h1_d2(2), G_d3bar_h2_d2(2),  &
   G_d3bar_h3_d2(2), G_d3bar_h1_d3(2), G_d3bar_h2_d3(2), G_d3bar_h3_d3(2), G_u1bar_hm2c_d1(2),  &
   G_u1bar_hm2c_d2(2), G_u1bar_hm2c_d3(2), G_u2bar_hm2c_d1(2), G_u2bar_hm2c_d2(2), G_u2bar_hm2c_d3 &
   (2), G_u3bar_hm2c_d1(2), G_u3bar_hm2c_d2(2), G_u3bar_hm2c_d3(2), G_e1bar_h1_e1(2 &
   ), G_e1bar_h2_e1(2), G_e1bar_h3_e1(2), G_e1bar_h1_e2(2), G_e1bar_h2_e2(2),  &
   G_e1bar_h3_e2(2), G_e1bar_h1_e3(2), G_e1bar_h2_e3(2), G_e1bar_h3_e3(2), G_e2bar_h1_e1(2),  &
   G_e2bar_h2_e1(2), G_e2bar_h3_e1(2), G_e2bar_h1_e2(2), G_e2bar_h2_e2(2), G_e2bar_h3_e2(2),  &
   G_e2bar_h1_e3(2), G_e2bar_h2_e3(2), G_e2bar_h3_e3(2), G_e3bar_h1_e1(2), G_e3bar_h2_e1(2),  &
   G_e3bar_h3_e1(2), G_e3bar_h1_e2(2), G_e3bar_h2_e2(2), G_e3bar_h3_e2(2), G_e3bar_h1_e3(2),  &
   G_e3bar_h2_e3(2), G_e3bar_h3_e3(2), G_nu1bar_hm2c_e1, G_nu1bar_hm2c_e2, G_nu1bar_hm2c_e3,  &
   G_nu2bar_hm2c_e1, G_nu2bar_hm2c_e2, G_nu2bar_hm2c_e3, G_nu3bar_hm2c_e1, G_nu3bar_hm2c_e2,  &
   G_nu3bar_hm2c_e3, G_u1bar_h1_u1(2), G_u1bar_h2_u1(2), G_u1bar_h3_u1(2), G_u1bar_h1_u2(2),  &
   G_u1bar_h2_u2(2), G_u1bar_h3_u2(2), G_u1bar_h1_u3(2), G_u1bar_h2_u3(2), G_u1bar_h3_u3(2),  &
   G_u2bar_h1_u1(2), G_u2bar_h2_u1(2), G_u2bar_h3_u1(2), G_u2bar_h1_u2(2), G_u2bar_h2_u2(2),  &
   G_u2bar_h3_u2(2), G_u2bar_h1_u3(2), G_u2bar_h2_u3(2), G_u2bar_h3_u3(2), G_u3bar_h1_u1(2),  &
   G_u3bar_h2_u1(2), G_u3bar_h3_u1(2), G_u3bar_h1_u2(2), G_u3bar_h2_u2(2), G_u3bar_h3_u2(2),  &
   G_u3bar_h1_u3(2), G_u3bar_h2_u3(2), G_u3bar_h3_u3(2), G_d1bar_hm2_u1(2), G_d1bar_hm2_u2(2),  &
   G_d1bar_hm2_u3(2), G_d2bar_hm2_u1(2), G_d2bar_hm2_u2(2), G_d2bar_hm2_u3(2), G_d3bar_hm2_u1(2 &
   ), G_d3bar_hm2_u2(2), G_d3bar_hm2_u3(2), G_e1bar_hm2_nu1, G_e1bar_hm2_nu2,  &
   G_e1bar_hm2_nu3, G_e2bar_hm2_nu1, G_e2bar_hm2_nu2, G_e2bar_hm2_nu3, G_e3bar_hm2_nu1,  &
   G_e3bar_hm2_nu2, G_e3bar_hm2_nu3, G_d1bar_g_1_d1(2), G_d1bar_a_1_d1(2), G_d1bar_z_1_d1(2),  &
   G_u1bar_wmc_d1, G_u1bar_wmc_d2, G_u1bar_wmc_d3, G_u2bar_wmc_d1, G_u2bar_wmc_d2, G_u2bar_wmc_d3 &
   , G_u3bar_wmc_d1, G_u3bar_wmc_d2, G_u3bar_wmc_d3, G_e1bar_a_1_e1(2),  &
   G_e1bar_z_1_e1(2), G_nu1bar_wmc_e1, G_nu1bar_wmc_e2, G_nu1bar_wmc_e3, G_nu2bar_wmc_e1,  &
   G_nu2bar_wmc_e2, G_nu2bar_wmc_e3, G_nu3bar_wmc_e1, G_nu3bar_wmc_e2, G_nu3bar_wmc_e3,  &
   G_u1bar_a_1_u1(2), G_d1bar_wm_1_u1, G_d1bar_wm_1_u2, G_d1bar_wm_1_u3, G_d2bar_wm_1_u1,  &
   G_d2bar_wm_1_u2, G_d2bar_wm_1_u3, G_d3bar_wm_1_u1, G_d3bar_wm_1_u2, G_d3bar_wm_1_u3,  &
   G_u1bar_z_1_u1(2), G_e1bar_wm_1_nu1, G_e1bar_wm_1_nu2, G_e1bar_wm_1_nu3, G_e2bar_wm_1_nu1,  &
   G_e2bar_wm_1_nu2, G_e2bar_wm_1_nu3, G_e3bar_wm_1_nu1, G_e3bar_wm_1_nu2, G_e3bar_wm_1_nu3,  &
   G_nu1bar_z_1_nu1, G_g_1_g_1_g_1, G_wmc_a_1_wm_1, G_wmc_wm_1_z_1, G_g_1_g_1_g_1_g_1,  &
   G_wmc_a_1_a_1_wm_1, G_wmc_a_1_wm_1_z_1, G_wmc_a_1_wm_1_z_1_1, G_wmc_wmc_wm_1_wm_1,  &
   G_wmc_wm_1_z_1_z_1

interface sec
   module procedure sec_re
   module procedure sec_cmplx
end interface sec

interface csc
   module procedure csc_re
   module procedure csc_cmplx
end interface csc

contains

function sec_re (x) result (y)
real(kind=default), intent(in) :: x
real(kind=default) :: y
   y = 1._default / cos (x)
end function sec_re

function sec_cmplx (x) result (y)
complex(kind=default), intent(in) :: x
complex(kind=default) :: y
   y = 1._default / cos (x)
end function sec_cmplx

function csc_re (x) result (y)
real(kind=default), intent(in) :: x
real(kind=default) :: y
   y = 1._default / cos (x)
end function csc_re

function csc_cmplx (x) result (y)
complex(kind=default), intent(in) :: x
complex(kind=default) :: y
   y = 1._default / cos (x)
end function csc_cmplx

end module parameters_hdms_sarah2_global