! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 6/30/2025 , 10:25:26
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 3.0.0
! Model name: hdms_sarah2
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 150
! --------------------------------------------------------------------------------
! 
! --------------------------------------------------------------------------------

module parameters_hdms_sarah2_cpl3
use parameters_hdms_sarah2_global
use parameters_hdms_sarah2_local
implicit none

contains

subroutine calc_cpl3
   G_d2bar_wm_1_u3 = (0,-0.5_default)*(((0,1)*g2*ZDL21*conjg(ZUL31))/Sqrt ( &
      2._default) + ((0,1)*g2*ZDL22*conjg(ZUL32))/Sqrt (2._default) + ((0,1)*g2*ZDL23*conjg( &
      ZUL33))/Sqrt (2._default))
   G_d3bar_wm_1_u1 = (0,-0.5_default)*(((0,1)*g2*ZDL31*conjg(ZUL11))/Sqrt ( &
      2._default) + ((0,1)*g2*ZDL32*conjg(ZUL12))/Sqrt (2._default) + ((0,1)*g2*ZDL33*conjg( &
      ZUL13))/Sqrt (2._default))
   G_d3bar_wm_1_u2 = (0,-0.5_default)*(((0,1)*g2*ZDL31*conjg(ZUL21))/Sqrt ( &
      2._default) + ((0,1)*g2*ZDL32*conjg(ZUL22))/Sqrt (2._default) + ((0,1)*g2*ZDL33*conjg( &
      ZUL23))/Sqrt (2._default))
   G_d3bar_wm_1_u3 = (0,-0.5_default)*(((0,1)*g2*ZDL31*conjg(ZUL31))/Sqrt ( &
      2._default) + ((0,1)*g2*ZDL32*conjg(ZUL32))/Sqrt (2._default) + ((0,1)*g2*ZDL33*conjg( &
      ZUL33))/Sqrt (2._default))
   G_u1bar_z_1_u1(1) = (0,-0.5_default)*((0,0.5_default)*g2*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*Sin(TW))
   G_u1bar_z_1_u1(2) = -0.3333333333333333_default*(g1*Sin(TW))
   G_e1bar_wm_1_nu1 = (g2*ZEL11)/(2._default*Sqrt (2._default))
   G_e1bar_wm_1_nu2 = (g2*ZEL12)/(2._default*Sqrt (2._default))
   G_e1bar_wm_1_nu3 = (g2*ZEL13)/(2._default*Sqrt (2._default))
   G_e2bar_wm_1_nu1 = (g2*ZEL21)/(2._default*Sqrt (2._default))
   G_e2bar_wm_1_nu2 = (g2*ZEL22)/(2._default*Sqrt (2._default))
   G_e2bar_wm_1_nu3 = (g2*ZEL23)/(2._default*Sqrt (2._default))
   G_e3bar_wm_1_nu1 = (g2*ZEL31)/(2._default*Sqrt (2._default))
   G_e3bar_wm_1_nu2 = (g2*ZEL32)/(2._default*Sqrt (2._default))
   G_e3bar_wm_1_nu3 = (g2*ZEL33)/(2._default*Sqrt (2._default))
   G_nu1bar_z_1_nu1 = (0,-0.5_default)*((0,0.5_default)*g2*Cos(TW) + (0,0.5_default &
      )*g1*Sin(TW))
   G_g_1_g_1_g_1 = ((0,-1)*g3)/Sqrt (2._default)
   G_wmc_a_1_wm_1 = (0,-1)*g2*Sin(TW)
   G_wmc_wm_1_z_1 = (0,1)*g2*Cos(TW)
   G_g_1_g_1_g_1_g_1 = -0.5_default*g3**2
   G_wmc_a_1_a_1_wm_1 = g2**2*Sin(TW)**2
   G_wmc_a_1_wm_1_z_1 = g2**2*Cos(TW)*Sin(TW)
   G_wmc_a_1_wm_1_z_1_1 = -(g2**2*Sin(2*TW))
   G_wmc_wmc_wm_1_wm_1 = g2**2
   G_wmc_wm_1_z_1_z_1 = -(g2**2*Cos(TW)**2)
end subroutine calc_cpl3

end module parameters_hdms_sarah2_cpl3