twoloophiggsmassdiags[[2]]={
{WoSSSS,{
{{{Ah, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}, {hh, i4, 3}},{{-1/2,WfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {Ah, i2}}, C[Ah, Ah, Ah, Ah]}, {{{Ah, i1}, {Ah, i3}, {hh, i4}}, C[Ah, Ah, hh]}, {{{Ah, i2}, {Ah, i3}, {hh, i4}}, C[Ah, Ah, hh]}}},
{{{Ah, i1, 3}, {Ah, i2, 3}, {Hm, i3, 2}, {conj[Hm], i4, 2}},{{-1/2,WfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {Ah, i2}}, C[Ah, Ah, Ah, Ah]}, {{{Ah, i1}, {Hm, i3}, {conj[Hm], i4}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, i2}, {Hm, i4}, {conj[Hm], i3}}, C[Ah, Hm, conj[Hm]]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {Hm, i3, 2}, {conj[Hm], i4, 2}},{{-1,WfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, Ah, hh]}, {{{Ah, i1}, {Hm, i3}, {conj[Hm], i4}}, C[Ah, Hm, conj[Hm]]}, {{{hh, i2}, {Hm, i4}, {conj[Hm], i3}}, C[hh, Hm, conj[Hm]]}}},
{{{hh, i1, 3}, {hh, i2, 3}, {Ah, i3, 3}, {Ah, i4, 3}},{{-1/4,WfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {hh, i1}, {hh, i2}}, C[Ah, Ah, hh, hh]}, {{{Ah, i3}, {Ah, i4}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, i3}, {Ah, i4}, {hh, i2}}, C[Ah, Ah, hh]}}},
{{{hh, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {hh, i4, 3}},{{-1/4,WfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {hh, i1}, {hh, i2}}, C[Ah, Ah, hh, hh]}, {{{hh, i1}, {hh, i3}, {hh, i4}}, C[hh, hh, hh]}, {{{hh, i2}, {hh, i3}, {hh, i4}}, C[hh, hh, hh]}}},
{{{hh, i1, 3}, {hh, i2, 3}, {Hm, i3, 2}, {conj[Hm], i4, 2}},{{-1/2,WfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {hh, i1}, {hh, i2}}, C[Ah, Ah, hh, hh]}, {{{hh, i1}, {Hm, i3}, {conj[Hm], i4}}, C[hh, Hm, conj[Hm]]}, {{{hh, i2}, {Hm, i4}, {conj[Hm], i3}}, C[hh, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Ah, i3, 3}, {Hm, i4, 2}},{{-1,WfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Ah, Hm, conj[Hm]]}, {{{Ah, i3}, {Hm, i4}, {conj[Hm], i1}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, i3}, {Hm, i2}, {conj[Hm], i4}}, C[Ah, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {hh, i3, 3}, {Hm, i4, 2}},{{-1,WfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Ah, Hm, conj[Hm]]}, {{{hh, i3}, {Hm, i4}, {conj[Hm], i1}}, C[hh, Hm, conj[Hm]]}, {{{hh, i3}, {Hm, i2}, {conj[Hm], i4}}, C[hh, Hm, conj[Hm]]}}}
}},
{XoSSS,{
{{{Ah, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}},{{1/4,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {Ah, i2}}, C[Ah, Ah, Ah, Ah]}, {{{Ah, i1}, {Ah, i2}, {Ah, i3}, {Ah, i3}}, C[Ah, Ah, Ah, Ah]}}},
{{{Ah, i1, 3}, {Ah, i2, 3}, {hh, i3, 3}},{{1/4,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {Ah, i2}}, C[Ah, Ah, Ah, Ah]}, {{{Ah, i1}, {Ah, i2}, {hh, i3}, {hh, i3}}, C[Ah, Ah, hh, hh]}}},
{{{Ah, i1, 3}, {Ah, i2, 3}, {Hm, i3, 2}},{{1/2,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {Ah, i2}}, C[Ah, Ah, Ah, Ah]}, {{{Ah, i1}, {Ah, i2}, {Hm, i3}, {conj[Hm], i3}}, C[Ah, Ah, Hm, conj[Hm]]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {Ah, i3, 3}},{{1/2,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, Ah, hh]}, {{{Ah, i1}, {Ah, i3}, {Ah, i3}, {hh, i2}}, C[Ah, Ah, Ah, hh]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}},{{1/2,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, Ah, hh]}, {{{Ah, i1}, {hh, i2}, {hh, i3}, {hh, i3}}, C[Ah, hh, hh, hh]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {Hm, i3, 2}},{{1,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, Ah, hh]}, {{{Ah, i1}, {hh, i2}, {Hm, i3}, {conj[Hm], i3}}, C[Ah, hh, Hm, conj[Hm]]}}},
{{{hh, i1, 3}, {hh, i2, 3}, {Ah, i3, 3}},{{1/4,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {hh, i1}, {hh, i2}}, C[Ah, Ah, hh, hh]}, {{{Ah, i3}, {Ah, i3}, {hh, i1}, {hh, i2}}, C[Ah, Ah, hh, hh]}}},
{{{hh, i1, 3}, {hh, i2, 3}, {hh, i3, 3}},{{1/4,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {hh, i1}, {hh, i2}}, C[Ah, Ah, hh, hh]}, {{{hh, i1}, {hh, i2}, {hh, i3}, {hh, i3}}, C[hh, hh, hh, hh]}}},
{{{hh, i1, 3}, {hh, i2, 3}, {Hm, i3, 2}},{{1/2,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {hh, i1}, {hh, i2}}, C[Ah, Ah, hh, hh]}, {{{hh, i1}, {hh, i2}, {Hm, i3}, {conj[Hm], i3}}, C[hh, hh, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Ah, i3, 3}},{{1/2,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Ah, Hm, conj[Hm]]}, {{{Ah, i3}, {Ah, i3}, {Hm, i2}, {conj[Hm], i1}}, C[Ah, Ah, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {hh, i3, 3}},{{1/2,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Ah, Hm, conj[Hm]]}, {{{hh, i3}, {hh, i3}, {Hm, i2}, {conj[Hm], i1}}, C[hh, hh, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Hm, i3, 2}},{{1,XfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, gE2}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Ah, Hm, conj[Hm]]}, {{{Hm, i2}, {Hm, i3}, {conj[Hm], i1}, {conj[Hm], i3}}, C[Hm, Hm, conj[Hm], conj[Hm]]}}}
}},
{YoSSSS,{
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {Ah, i4, 3}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{Ah, i4}, {Ah, i4}, {hh, i2}, {hh, i3}}, C[Ah, Ah, hh, hh]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {hh, i4, 3}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{hh, i2}, {hh, i3}, {hh, i4}, {hh, i4}}, C[hh, hh, hh, hh]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {Hm, i4, 2}},{{-1,YfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{hh, i2}, {hh, i3}, {Hm, i4}, {conj[Hm], i4}}, C[hh, hh, Hm, conj[Hm]]}}},
{{{hh, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}, {Ah, i4, 3}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i2}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i3}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, i2}, {Ah, i3}, {Ah, i4}, {Ah, i4}}, C[Ah, Ah, Ah, Ah]}}},
{{{hh, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}, {hh, i4, 3}},{{-1/2,YfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i2}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i3}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, i2}, {Ah, i3}, {hh, i4}, {hh, i4}}, C[Ah, Ah, hh, hh]}}},
{{{hh, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}, {Hm, i4, 2}},{{-1,YfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i2}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i3}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, i2}, {Ah, i3}, {Hm, i4}, {conj[Hm], i4}}, C[Ah, Ah, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Hm, i3, 2}, {Ah, i4, 3}},{{-1,YfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Hm, i3}, {conj[Hm], i1}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, i4}, {Ah, i4}, {Hm, i2}, {conj[Hm], i3}}, C[Ah, Ah, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Hm, i3, 2}, {hh, i4, 3}},{{-1,YfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Hm, i3}, {conj[Hm], i1}}, C[Ah, Hm, conj[Hm]]}, {{{hh, i4}, {hh, i4}, {Hm, i2}, {conj[Hm], i3}}, C[hh, hh, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Hm, i3, 2}, {Hm, i4, 2}},{{-2,YfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Hm, i3}, {conj[Hm], i1}}, C[Ah, Hm, conj[Hm]]}, {{{Hm, i2}, {Hm, i4}, {conj[Hm], i3}, {conj[Hm], i4}}, C[Hm, Hm, conj[Hm], conj[Hm]]}}}
}},
{ZoSSSS,{
{{{Ah, i1, 3}, {hh, i2, 3}, {Ah, i3, 3}, {hh, i4, 3}},{{-1,ZfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i3}, {hh, i4}}, C[Ah, Ah, hh]}, {{{Ah, i1}, {Ah, i3}, {hh, i2}, {hh, i4}}, C[Ah, Ah, hh, hh]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {Hm, i3, 2}, {conj[Hm], i4, 2}},{{-2,ZfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Hm, i3}, {conj[Hm], i4}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, i1}, {hh, i2}, {Hm, i4}, {conj[Hm], i3}}, C[Ah, hh, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Hm, i3, 2}, {conj[Hm], i4, 2}},{{-1,ZfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Hm, i3}, {conj[Hm], i4}}, C[Ah, Hm, conj[Hm]]}, {{{Hm, i2}, {Hm, i4}, {conj[Hm], i1}, {conj[Hm], i3}}, C[Hm, Hm, conj[Hm], conj[Hm]]}}}
}},
{SoSSS,{
{{{Ah, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}},{{1/6,SfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {Ah, i2}, {Ah, i3}}, C[Ah, Ah, Ah, Ah]}, {{{Ah, gE2}, {Ah, i1}, {Ah, i2}, {Ah, i3}}, C[Ah, Ah, Ah, Ah]}}},
{{{Ah, i1, 3}, {Ah, i2, 3}, {hh, i3, 3}},{{1/2,SfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {Ah, i2}, {hh, i3}}, C[Ah, Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {Ah, i2}, {hh, i3}}, C[Ah, Ah, Ah, hh]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}},{{1/2,SfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}, {hh, i3}}, C[Ah, Ah, hh, hh]}, {{{Ah, gE2}, {Ah, i1}, {hh, i2}, {hh, i3}}, C[Ah, Ah, hh, hh]}}},
{{{Ah, i1, 3}, {Hm, i2, 2}, {conj[Hm], i3, 2}},{{1,SfSSS,{0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {Hm, i2}, {conj[Hm], i3}}, C[Ah, Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Ah, i1}, {Hm, i3}, {conj[Hm], i2}}, C[Ah, Ah, Hm, conj[Hm]]}}},
{{{hh, i1, 3}, {hh, i2, 3}, {hh, i3, 3}},{{1/6,SfSSS,{0, 0}}},{{{{Ah, gE1}, {hh, i1}, {hh, i2}, {hh, i3}}, C[Ah, hh, hh, hh]}, {{{Ah, gE2}, {hh, i1}, {hh, i2}, {hh, i3}}, C[Ah, hh, hh, hh]}}},
{{{hh, i1, 3}, {Hm, i2, 2}, {conj[Hm], i3, 2}},{{1,SfSSS,{0, 0}}},{{{{Ah, gE1}, {hh, i1}, {Hm, i2}, {conj[Hm], i3}}, C[Ah, hh, Hm, conj[Hm]]}, {{{Ah, gE2}, {hh, i1}, {Hm, i3}, {conj[Hm], i2}}, C[Ah, hh, Hm, conj[Hm]]}}}
}},
{UoSSSS,{
{{{Ah, i1, 3}, {hh, i2, 3}, {Ah, i3, 3}, {Ah, i4, 3}},{{-1,UfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {Ah, i3}, {Ah, i4}}, C[Ah, Ah, Ah, Ah]}, {{{Ah, i3}, {Ah, i4}, {hh, i2}}, C[Ah, Ah, hh]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {hh, i4, 3}},{{-1,UfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {hh, i3}, {hh, i4}}, C[Ah, Ah, hh, hh]}, {{{hh, i2}, {hh, i3}, {hh, i4}}, C[hh, hh, hh]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {Hm, i3, 2}, {conj[Hm], i4, 2}},{{-2,UfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {Hm, i3}, {conj[Hm], i4}}, C[Ah, Ah, Hm, conj[Hm]]}, {{{hh, i2}, {Hm, i4}, {conj[Hm], i3}}, C[hh, Hm, conj[Hm]]}}},
{{{hh, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}, {hh, i4, 3}},{{-2,UfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i2}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i3}, {hh, i1}, {hh, i4}}, C[Ah, Ah, hh, hh]}, {{{Ah, i2}, {Ah, i3}, {hh, i4}}, C[Ah, Ah, hh]}}},
{{{hh, i1, 3}, {Ah, i2, 3}, {Hm, i3, 2}, {conj[Hm], i4, 2}},{{-2,UfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Ah, i2}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {hh, i1}, {Hm, i3}, {conj[Hm], i4}}, C[Ah, hh, Hm, conj[Hm]]}, {{{Ah, i2}, {Hm, i4}, {conj[Hm], i3}}, C[Ah, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Ah, i3, 3}, {Hm, i4, 2}},{{-4,UfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Ah, i3}, {Hm, i4}, {conj[Hm], i1}}, C[Ah, Ah, Hm, conj[Hm]]}, {{{Ah, i3}, {Hm, i2}, {conj[Hm], i4}}, C[Ah, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {hh, i3, 3}, {Hm, i4, 2}},{{-4,UfSSSS,{0, 0, 0}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {hh, i3}, {Hm, i4}, {conj[Hm], i1}}, C[Ah, hh, Hm, conj[Hm]]}, {{{hh, i3}, {Hm, i2}, {conj[Hm], i4}}, C[hh, Hm, conj[Hm]]}}}
}},
{VoSSSSS,{
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {Ah, i4, 3}, {Ah, i5, 3}},{{1/2,VfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{Ah, i4}, {Ah, i5}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, i4}, {Ah, i5}, {hh, i3}}, C[Ah, Ah, hh]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {hh, i4, 3}, {hh, i5, 3}},{{1/2,VfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{hh, i2}, {hh, i4}, {hh, i5}}, C[hh, hh, hh]}, {{{hh, i3}, {hh, i4}, {hh, i5}}, C[hh, hh, hh]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {Hm, i4, 2}, {conj[Hm], i5, 2}},{{1,VfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{hh, i2}, {Hm, i4}, {conj[Hm], i5}}, C[hh, Hm, conj[Hm]]}, {{{hh, i3}, {Hm, i5}, {conj[Hm], i4}}, C[hh, Hm, conj[Hm]]}}},
{{{hh, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}, {Ah, i4, 3}, {hh, i5, 3}},{{1,VfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Ah, i2}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i3}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, i2}, {Ah, i4}, {hh, i5}}, C[Ah, Ah, hh]}, {{{Ah, i3}, {Ah, i4}, {hh, i5}}, C[Ah, Ah, hh]}}},
{{{hh, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}, {Hm, i4, 2}, {conj[Hm], i5, 2}},{{1,VfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Ah, i2}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i3}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, i2}, {Hm, i4}, {conj[Hm], i5}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, i3}, {Hm, i5}, {conj[Hm], i4}}, C[Ah, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Hm, i3, 2}, {Ah, i4, 3}, {conj[Hm], i5, 2}},{{2,VfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Hm, i3}, {conj[Hm], i1}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, i4}, {Hm, i2}, {conj[Hm], i5}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, i4}, {Hm, i5}, {conj[Hm], i3}}, C[Ah, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Hm, i3, 2}, {hh, i4, 3}, {conj[Hm], i5, 2}},{{2,VfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Hm, i3}, {conj[Hm], i1}}, C[Ah, Hm, conj[Hm]]}, {{{hh, i4}, {Hm, i2}, {conj[Hm], i5}}, C[hh, Hm, conj[Hm]]}, {{{hh, i4}, {Hm, i5}, {conj[Hm], i3}}, C[hh, Hm, conj[Hm]]}}}
}},
{MoSSSSS,{
{{{Ah, i1, 3}, {Ah, i2, 3}, {hh, i3, 3}, {hh, i4, 3}, {hh, i5, 3}},{{1,MfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i2}, {hh, i4}}, C[Ah, Ah, hh]}, {{{Ah, i1}, {Ah, i2}, {hh, i5}}, C[Ah, Ah, hh]}, {{{hh, i3}, {hh, i4}, {hh, i5}}, C[hh, hh, hh]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {Ah, i4, 3}, {Ah, i5, 3}},{{1,MfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i4}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, i1}, {Ah, i5}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, i4}, {Ah, i5}, {hh, i3}}, C[Ah, Ah, hh]}}},
{{{Ah, i1, 3}, {Hm, i2, 2}, {hh, i3, 3}, {conj[Hm], i4, 2}, {Hm, i5, 2}},{{4,MfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Hm, i2}, {conj[Hm], i4}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, i1}, {Hm, i5}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{hh, i3}, {Hm, i4}, {conj[Hm], i5}}, C[hh, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {conj[Hm], i3, 2}, {Hm, i4, 2}, {Ah, i5, 3}},{{1,MfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i3}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Hm, i4}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, i5}, {Hm, i2}, {conj[Hm], i1}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, i5}, {Hm, i3}, {conj[Hm], i4}}, C[Ah, Hm, conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {conj[Hm], i3, 2}, {Hm, i4, 2}, {hh, i5, 3}},{{1,MfSSSSS,{0, 0, 0, 0}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i3}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Hm, i4}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{hh, i5}, {Hm, i2}, {conj[Hm], i1}}, C[hh, Hm, conj[Hm]]}, {{{hh, i5}, {Hm, i3}, {conj[Hm], i4}}, C[hh, Hm, conj[Hm]]}}}
}},
{WoSSFF,{
{{{Ah, i1, 3}, {Ah, i2, 3}, {Fd, i3, 3}, {bar[Fd], i4, 3}},{{-3/2*Mass[Fd,i3]*Mass[bar[Fd],i4],WfSSFbFb,{0, L, L}},{-3/2,WfSSFF,{0, L, R}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {Ah, i2}}, C[Ah, Ah, Ah, Ah]}, {{{bar[Fd], i4}, {Fd, i3}, {Ah, i1}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i4}, {Ah, i2}}, C[Ah, Fd, bar[Fd]]}}},
{{{Ah, i1, 3}, {Ah, i2, 3}, {Fe, i3, 3}, {bar[Fe], i4, 3}},{{-1/2*Mass[Fe,i3]*Mass[bar[Fe],i4],WfSSFbFb,{0, L, L}},{-1/2,WfSSFF,{0, L, R}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {Ah, i2}}, C[Ah, Ah, Ah, Ah]}, {{{bar[Fe], i4}, {Fe, i3}, {Ah, i1}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i4}, {Ah, i2}}, C[Ah, Fe, bar[Fe]]}}},
{{{Ah, i1, 3}, {Ah, i2, 3}, {Fu, i3, 3}, {bar[Fu], i4, 3}},{{-3/2*Mass[Fu,i3]*Mass[bar[Fu],i4],WfSSFbFb,{0, L, L}},{-3/2,WfSSFF,{0, L, R}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {Ah, i2}}, C[Ah, Ah, Ah, Ah]}, {{{bar[Fu], i4}, {Fu, i3}, {Ah, i1}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i4}, {Ah, i2}}, C[Ah, Fu, bar[Fu]]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {Fd, i3, 3}, {bar[Fd], i4, 3}},{{-3*Mass[Fd,i3]*Mass[bar[Fd],i4],WfSSFbFb,{0, L, L}},{-3,WfSSFF,{0, L, R}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, Ah, hh]}, {{{bar[Fd], i4}, {Fd, i3}, {Ah, i1}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i4}, {hh, i2}}, C[Fd, hh, bar[Fd]]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {Fe, i3, 3}, {bar[Fe], i4, 3}},{{-1*Mass[Fe,i3]*Mass[bar[Fe],i4],WfSSFbFb,{0, L, L}},{-1,WfSSFF,{0, L, R}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, Ah, hh]}, {{{bar[Fe], i4}, {Fe, i3}, {Ah, i1}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i4}, {hh, i2}}, C[Fe, hh, bar[Fe]]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {Fu, i3, 3}, {bar[Fu], i4, 3}},{{-3*Mass[Fu,i3]*Mass[bar[Fu],i4],WfSSFbFb,{0, L, L}},{-3,WfSSFF,{0, L, R}}},{{{{Ah, gE1}, {Ah, gE2}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, Ah, hh]}, {{{bar[Fu], i4}, {Fu, i3}, {Ah, i1}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i4}, {hh, i2}}, C[Fu, hh, bar[Fu]]}}},
{{{hh, i1, 3}, {hh, i2, 3}, {Fd, i3, 3}, {bar[Fd], i4, 3}},{{-3/2*Mass[Fd,i3]*Mass[bar[Fd],i4],WfSSFbFb,{0, L, L}},{-3/2,WfSSFF,{0, L, R}}},{{{{Ah, gE1}, {Ah, gE2}, {hh, i1}, {hh, i2}}, C[Ah, Ah, hh, hh]}, {{{bar[Fd], i4}, {Fd, i3}, {hh, i1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i4}, {hh, i2}}, C[Fd, hh, bar[Fd]]}}},
{{{hh, i1, 3}, {hh, i2, 3}, {Fe, i3, 3}, {bar[Fe], i4, 3}},{{-1/2*Mass[Fe,i3]*Mass[bar[Fe],i4],WfSSFbFb,{0, L, L}},{-1/2,WfSSFF,{0, L, R}}},{{{{Ah, gE1}, {Ah, gE2}, {hh, i1}, {hh, i2}}, C[Ah, Ah, hh, hh]}, {{{bar[Fe], i4}, {Fe, i3}, {hh, i1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i4}, {hh, i2}}, C[Fe, hh, bar[Fe]]}}},
{{{hh, i1, 3}, {hh, i2, 3}, {Fu, i3, 3}, {bar[Fu], i4, 3}},{{-3/2*Mass[Fu,i3]*Mass[bar[Fu],i4],WfSSFbFb,{0, L, L}},{-3/2,WfSSFF,{0, L, R}}},{{{{Ah, gE1}, {Ah, gE2}, {hh, i1}, {hh, i2}}, C[Ah, Ah, hh, hh]}, {{{bar[Fu], i4}, {Fu, i3}, {hh, i1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i4}, {hh, i2}}, C[Fu, hh, bar[Fu]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Fd, i3, 3}, {bar[Fu], i4, 3}},{{-3*Mass[Fd,i3]*Mass[bar[Fu],i4],WfSSFbFb,{0, L, L}},{-3,WfSSFF,{0, L, R}}},{{{{Ah, gE1}, {Ah, gE2}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Ah, Hm, conj[Hm]]}, {{{bar[Fu], i4}, {Fd, i3}, {conj[Hm], i1}}, C[Fd, bar[Fu], conj[Hm]]}, {{{bar[Fd], i3}, {Fu, i4}, {Hm, i2}}, C[Fu, Hm, bar[Fd]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Fe, i3, 3}, {bar[Fv], i4, 3}},{{-1*Mass[Fe,i3]*Mass[bar[Fv],i4],WfSSFbFb,{0, L, L}},{-1,WfSSFF,{0, L, R}}},{{{{Ah, gE1}, {Ah, gE2}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Ah, Hm, conj[Hm]]}, {{{bar[Fv], i4}, {Fe, i3}, {conj[Hm], i1}}, C[Fe, bar[Fv], conj[Hm]]}, {{{bar[Fe], i3}, {Fv, i4}, {Hm, i2}}, C[Fv, Hm, bar[Fe]]}}}
}},
{MoFFFFS,{
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {bar[Fd], i3, 3}, {Fd, i4, 3}, {Ah, i5, 3}},{{3*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[bar[Fd],i3]*Mass[Fd,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fd],i2]*Mass[bar[Fd],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fd],i2]*Mass[Fd,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fd],i3]*Mass[Fd,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fd], i3}, {Fd, i1}, {Ah, gE1}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i2}, {Fd, i4}, {Ah, gE2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i2}, {Ah, i5}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i3}, {Ah, i5}}, C[Ah, Fd, bar[Fd]]}}},
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {bar[Fd], i3, 3}, {Fd, i4, 3}, {hh, i5, 3}},{{3*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[bar[Fd],i3]*Mass[Fd,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fd],i2]*Mass[bar[Fd],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fd],i2]*Mass[Fd,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fd],i3]*Mass[Fd,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fd], i3}, {Fd, i1}, {Ah, gE1}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i2}, {Fd, i4}, {Ah, gE2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i2}, {hh, i5}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i3}, {hh, i5}}, C[Fd, hh, bar[Fd]]}}},
{{{Fd, i1, 3}, {bar[Fu], i2, 3}, {bar[Fd], i3, 3}, {Fu, i4, 3}, {Hm, i5, 2}},{{3*Mass[Fd,i1]*Mass[bar[Fu],i2]*Mass[bar[Fd],i3]*Mass[Fu,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fu],i2]*Mass[bar[Fd],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fu],i2]*Mass[Fu,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fd],i3]*Mass[Fu,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fd], i3}, {Fd, i1}, {Ah, gE1}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fu], i2}, {Fu, i4}, {Ah, gE2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fd], i1}, {Fu, i2}, {Hm, i5}}, C[Fu, Hm, bar[Fd]]}, {{{bar[Fu], i4}, {Fd, i3}, {conj[Hm], i5}}, C[Fd, bar[Fu], conj[Hm]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {bar[Fe], i3, 3}, {Fe, i4, 3}, {Ah, i5, 3}},{{1*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[bar[Fe],i3]*Mass[Fe,i4],MfFbFbFbFbS,{L, L, L, L}},{2*Mass[bar[Fe],i2]*Mass[bar[Fe],i3],MfFFbFbFS,{L, R, R, L}},{2*Mass[bar[Fe],i2]*Mass[Fe,i4],MfFFbFFbS,{L, R, R, R}},{2*Mass[bar[Fe],i3]*Mass[Fe,i4],MfFFFbFbS,{L, L, R, L}},{1,MfFFFFS,{L, L, R, R}}},{{{{bar[Fe], i3}, {Fe, i1}, {Ah, gE1}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i2}, {Fe, i4}, {Ah, gE2}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i2}, {Ah, i5}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i3}, {Ah, i5}}, C[Ah, Fe, bar[Fe]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {bar[Fe], i3, 3}, {Fe, i4, 3}, {hh, i5, 3}},{{1*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[bar[Fe],i3]*Mass[Fe,i4],MfFbFbFbFbS,{L, L, L, L}},{2*Mass[bar[Fe],i2]*Mass[bar[Fe],i3],MfFFbFbFS,{L, R, R, L}},{2*Mass[bar[Fe],i2]*Mass[Fe,i4],MfFFbFFbS,{L, R, R, R}},{2*Mass[bar[Fe],i3]*Mass[Fe,i4],MfFFFbFbS,{L, L, R, L}},{1,MfFFFFS,{L, L, R, R}}},{{{{bar[Fe], i3}, {Fe, i1}, {Ah, gE1}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i2}, {Fe, i4}, {Ah, gE2}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i2}, {hh, i5}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i3}, {hh, i5}}, C[Fe, hh, bar[Fe]]}}},
{{{Fu, i1, 3}, {bar[Fd], i2, 3}, {bar[Fu], i3, 3}, {Fd, i4, 3}, {conj[Hm], i5, 2}},{{3*Mass[Fu,i1]*Mass[bar[Fd],i2]*Mass[bar[Fu],i3]*Mass[Fd,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fd],i2]*Mass[bar[Fu],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fd],i2]*Mass[Fd,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fu],i3]*Mass[Fd,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fu], i3}, {Fu, i1}, {Ah, gE1}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fd], i2}, {Fd, i4}, {Ah, gE2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fu], i1}, {Fd, i2}, {conj[Hm], i5}}, C[Fd, bar[Fu], conj[Hm]]}, {{{bar[Fd], i4}, {Fu, i3}, {Hm, i5}}, C[Fu, Hm, bar[Fd]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {bar[Fu], i3, 3}, {Fu, i4, 3}, {Ah, i5, 3}},{{3*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[bar[Fu],i3]*Mass[Fu,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fu],i2]*Mass[bar[Fu],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fu],i2]*Mass[Fu,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fu],i3]*Mass[Fu,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fu], i3}, {Fu, i1}, {Ah, gE1}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i2}, {Fu, i4}, {Ah, gE2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i2}, {Ah, i5}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i3}, {Ah, i5}}, C[Ah, Fu, bar[Fu]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {bar[Fu], i3, 3}, {Fu, i4, 3}, {hh, i5, 3}},{{3*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[bar[Fu],i3]*Mass[Fu,i4],MfFbFbFbFbS,{L, L, L, L}},{6*Mass[bar[Fu],i2]*Mass[bar[Fu],i3],MfFFbFbFS,{L, R, R, L}},{6*Mass[bar[Fu],i2]*Mass[Fu,i4],MfFFbFFbS,{L, R, R, R}},{6*Mass[bar[Fu],i3]*Mass[Fu,i4],MfFFFbFbS,{L, L, R, L}},{3,MfFFFFS,{L, L, R, R}}},{{{{bar[Fu], i3}, {Fu, i1}, {Ah, gE1}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i2}, {Fu, i4}, {Ah, gE2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i2}, {hh, i5}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i3}, {hh, i5}}, C[Fu, hh, bar[Fu]]}}}
}},
{MoSFSFF,{
{{{Ah, i1, 3}, {Fd, i2, 3}, {hh, i3, 3}, {bar[Fd], i4, 3}, {Fd, i5, 3}},{{6*Mass[Fd,i2]*Mass[bar[Fd],i4]*Mass[Fd,i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[bar[Fd],i4],MfSFSFbF,{0, L, R, L}},{6*Mass[Fd,i5],MfSFSFFb,{0, L, R, R}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{bar[Fd], i4}, {Fd, i2}, {Ah, gE2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i2}, {Fd, i5}, {Ah, i1}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i5}, {Fd, i4}, {hh, i3}}, C[Fd, hh, bar[Fd]]}}},
{{{Ah, i1, 3}, {Fe, i2, 3}, {hh, i3, 3}, {bar[Fe], i4, 3}, {Fe, i5, 3}},{{2*Mass[Fe,i2]*Mass[bar[Fe],i4]*Mass[Fe,i5],MfSFbSFbFb,{0, L, L, L}},{4*Mass[bar[Fe],i4],MfSFSFbF,{0, L, R, L}},{2*Mass[Fe,i5],MfSFSFFb,{0, L, R, R}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{bar[Fe], i4}, {Fe, i2}, {Ah, gE2}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i2}, {Fe, i5}, {Ah, i1}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i5}, {Fe, i4}, {hh, i3}}, C[Fe, hh, bar[Fe]]}}},
{{{Ah, i1, 3}, {Fu, i2, 3}, {hh, i3, 3}, {bar[Fu], i4, 3}, {Fu, i5, 3}},{{6*Mass[Fu,i2]*Mass[bar[Fu],i4]*Mass[Fu,i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[bar[Fu],i4],MfSFSFbF,{0, L, R, L}},{6*Mass[Fu,i5],MfSFSFFb,{0, L, R, R}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{bar[Fu], i4}, {Fu, i2}, {Ah, gE2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i2}, {Fu, i5}, {Ah, i1}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i5}, {Fu, i4}, {hh, i3}}, C[Fu, hh, bar[Fu]]}}},
{{{hh, i1, 3}, {Fd, i2, 3}, {Ah, i3, 3}, {bar[Fd], i4, 3}, {Fd, i5, 3}},{{6*Mass[Fd,i2]*Mass[bar[Fd],i4]*Mass[Fd,i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[bar[Fd],i4],MfSFSFbF,{0, L, R, L}},{6*Mass[Fd,i5],MfSFSFFb,{0, L, R, R}}},{{{{Ah, gE1}, {Ah, i3}, {hh, i1}}, C[Ah, Ah, hh]}, {{{bar[Fd], i4}, {Fd, i2}, {Ah, gE2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i2}, {Fd, i5}, {hh, i1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i5}, {Fd, i4}, {Ah, i3}}, C[Ah, Fd, bar[Fd]]}}},
{{{hh, i1, 3}, {Fe, i2, 3}, {Ah, i3, 3}, {bar[Fe], i4, 3}, {Fe, i5, 3}},{{2*Mass[Fe,i2]*Mass[bar[Fe],i4]*Mass[Fe,i5],MfSFbSFbFb,{0, L, L, L}},{4*Mass[bar[Fe],i4],MfSFSFbF,{0, L, R, L}},{2*Mass[Fe,i5],MfSFSFFb,{0, L, R, R}}},{{{{Ah, gE1}, {Ah, i3}, {hh, i1}}, C[Ah, Ah, hh]}, {{{bar[Fe], i4}, {Fe, i2}, {Ah, gE2}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i2}, {Fe, i5}, {hh, i1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i5}, {Fe, i4}, {Ah, i3}}, C[Ah, Fe, bar[Fe]]}}},
{{{hh, i1, 3}, {Fu, i2, 3}, {Ah, i3, 3}, {bar[Fu], i4, 3}, {Fu, i5, 3}},{{6*Mass[Fu,i2]*Mass[bar[Fu],i4]*Mass[Fu,i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[bar[Fu],i4],MfSFSFbF,{0, L, R, L}},{6*Mass[Fu,i5],MfSFSFFb,{0, L, R, R}}},{{{{Ah, gE1}, {Ah, i3}, {hh, i1}}, C[Ah, Ah, hh]}, {{{bar[Fu], i4}, {Fu, i2}, {Ah, gE2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i2}, {Fu, i5}, {hh, i1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i5}, {Fu, i4}, {Ah, i3}}, C[Ah, Fu, bar[Fu]]}}},
{{{Hm, i1, 2}, {Fu, i2, 3}, {conj[Hm], i3, 2}, {bar[Fu], i4, 3}, {Fd, i5, 3}},{{6*Mass[Fu,i2]*Mass[bar[Fu],i4]*Mass[Fd,i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[bar[Fu],i4],MfSFSFbF,{0, L, R, L}},{6*Mass[Fd,i5],MfSFSFFb,{0, L, R, R}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i3}}, C[Ah, Hm, conj[Hm]]}, {{{bar[Fu], i4}, {Fu, i2}, {Ah, gE2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i2}, {Fd, i5}, {conj[Hm], i1}}, C[Fd, bar[Fu], conj[Hm]]}, {{{bar[Fd], i5}, {Fu, i4}, {Hm, i3}}, C[Fu, Hm, bar[Fd]]}}},
{{{Hm, i1, 2}, {bar[Fd], i2, 3}, {conj[Hm], i3, 2}, {Fd, i4, 3}, {bar[Fu], i5, 3}},{{6*Mass[bar[Fd],i2]*Mass[Fd,i4]*Mass[bar[Fu],i5],MfSFbSFbFb,{0, L, L, L}},{12*Mass[Fd,i4],MfSFSFbF,{0, L, R, L}},{6*Mass[bar[Fu],i5],MfSFSFFb,{0, L, R, R}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i3}}, C[Ah, Hm, conj[Hm]]}, {{{bar[Fd], i2}, {Fd, i4}, {Ah, gE2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fu], i5}, {Fd, i2}, {conj[Hm], i1}}, C[Fd, bar[Fu], conj[Hm]]}, {{{bar[Fd], i4}, {Fu, i5}, {Hm, i3}}, C[Fu, Hm, bar[Fd]]}}},
{{{Hm, i1, 2}, {bar[Fe], i2, 3}, {conj[Hm], i3, 2}, {Fe, i4, 3}, {bar[Fv], i5, 3}},{{2*Mass[bar[Fe],i2]*Mass[Fe,i4]*Mass[bar[Fv],i5],MfSFbSFbFb,{0, L, L, L}},{4*Mass[Fe,i4],MfSFSFbF,{0, L, R, L}},{2*Mass[bar[Fv],i5],MfSFSFFb,{0, L, R, R}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i3}}, C[Ah, Hm, conj[Hm]]}, {{{bar[Fe], i2}, {Fe, i4}, {Ah, gE2}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fv], i5}, {Fe, i2}, {conj[Hm], i1}}, C[Fe, bar[Fv], conj[Hm]]}, {{{bar[Fe], i4}, {Fv, i5}, {Hm, i3}}, C[Fv, Hm, bar[Fe]]}}}
}},
{VoSSSFF,{
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {Fd, i4, 3}, {bar[Fd], i5, 3}},{{3*Mass[Fd,i4]*Mass[bar[Fd],i5],VfSSSFbFb,{0, 0, L, L}},{3,VfSSSFF,{0, 0, L, R}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{bar[Fd], i5}, {Fd, i4}, {hh, i2}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i5}, {hh, i3}}, C[Fd, hh, bar[Fd]]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {Fe, i4, 3}, {bar[Fe], i5, 3}},{{1*Mass[Fe,i4]*Mass[bar[Fe],i5],VfSSSFbFb,{0, 0, L, L}},{1,VfSSSFF,{0, 0, L, R}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{bar[Fe], i5}, {Fe, i4}, {hh, i2}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i5}, {hh, i3}}, C[Fe, hh, bar[Fe]]}}},
{{{Ah, i1, 3}, {hh, i2, 3}, {hh, i3, 3}, {Fu, i4, 3}, {bar[Fu], i5, 3}},{{3*Mass[Fu,i4]*Mass[bar[Fu],i5],VfSSSFbFb,{0, 0, L, L}},{3,VfSSSFF,{0, 0, L, R}}},{{{{Ah, gE1}, {Ah, i1}, {hh, i2}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i1}, {hh, i3}}, C[Ah, Ah, hh]}, {{{bar[Fu], i5}, {Fu, i4}, {hh, i2}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i5}, {hh, i3}}, C[Fu, hh, bar[Fu]]}}},
{{{hh, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}, {Fd, i4, 3}, {bar[Fd], i5, 3}},{{3*Mass[Fd,i4]*Mass[bar[Fd],i5],VfSSSFbFb,{0, 0, L, L}},{3,VfSSSFF,{0, 0, L, R}}},{{{{Ah, gE1}, {Ah, i2}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i3}, {hh, i1}}, C[Ah, Ah, hh]}, {{{bar[Fd], i5}, {Fd, i4}, {Ah, i2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i5}, {Ah, i3}}, C[Ah, Fd, bar[Fd]]}}},
{{{hh, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}, {Fe, i4, 3}, {bar[Fe], i5, 3}},{{1*Mass[Fe,i4]*Mass[bar[Fe],i5],VfSSSFbFb,{0, 0, L, L}},{1,VfSSSFF,{0, 0, L, R}}},{{{{Ah, gE1}, {Ah, i2}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i3}, {hh, i1}}, C[Ah, Ah, hh]}, {{{bar[Fe], i5}, {Fe, i4}, {Ah, i2}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i5}, {Ah, i3}}, C[Ah, Fe, bar[Fe]]}}},
{{{hh, i1, 3}, {Ah, i2, 3}, {Ah, i3, 3}, {Fu, i4, 3}, {bar[Fu], i5, 3}},{{3*Mass[Fu,i4]*Mass[bar[Fu],i5],VfSSSFbFb,{0, 0, L, L}},{3,VfSSSFF,{0, 0, L, R}}},{{{{Ah, gE1}, {Ah, i2}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, gE2}, {Ah, i3}, {hh, i1}}, C[Ah, Ah, hh]}, {{{bar[Fu], i5}, {Fu, i4}, {Ah, i2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i5}, {Ah, i3}}, C[Ah, Fu, bar[Fu]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Hm, i3, 2}, {Fu, i4, 3}, {bar[Fd], i5, 3}},{{6*Mass[Fu,i4]*Mass[bar[Fd],i5],VfSSSFbFb,{0, 0, L, L}},{6,VfSSSFF,{0, 0, L, R}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Hm, i3}, {conj[Hm], i1}}, C[Ah, Hm, conj[Hm]]}, {{{bar[Fd], i5}, {Fu, i4}, {Hm, i2}}, C[Fu, Hm, bar[Fd]]}, {{{bar[Fu], i4}, {Fd, i5}, {conj[Hm], i3}}, C[Fd, bar[Fu], conj[Hm]]}}},
{{{Hm, i1, 2}, {conj[Hm], i2, 2}, {Hm, i3, 2}, {Fv, i4, 3}, {bar[Fe], i5, 3}},{{2*Mass[Fv,i4]*Mass[bar[Fe],i5],VfSSSFbFb,{0, 0, L, L}},{2,VfSSSFF,{0, 0, L, R}}},{{{{Ah, gE1}, {Hm, i1}, {conj[Hm], i2}}, C[Ah, Hm, conj[Hm]]}, {{{Ah, gE2}, {Hm, i3}, {conj[Hm], i1}}, C[Ah, Hm, conj[Hm]]}, {{{bar[Fe], i5}, {Fv, i4}, {Hm, i2}}, C[Fv, Hm, bar[Fe]]}, {{{bar[Fv], i4}, {Fe, i5}, {conj[Hm], i3}}, C[Fe, bar[Fv], conj[Hm]]}}}
}},
{VoFFFFS,{
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {Fd, i3, 3}, {bar[Fd], i4, 3}, {Ah, i5, 3}},{{6*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[Fd,i3]*Mass[bar[Fd],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fd,i1]*Mass[Fd,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fd,i1]*Mass[bar[Fd],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fd],i2]*Mass[Fd,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fd,i3]*Mass[bar[Fd],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fd], i2}, {Fd, i1}, {Ah, gE1}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i3}, {Ah, gE2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i2}, {Ah, i5}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i4}, {Ah, i5}}, C[Ah, Fd, bar[Fd]]}}},
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {Fd, i3, 3}, {bar[Fd], i4, 3}, {hh, i5, 3}},{{6*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[Fd,i3]*Mass[bar[Fd],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fd,i1]*Mass[Fd,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fd,i1]*Mass[bar[Fd],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fd],i2]*Mass[Fd,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fd,i3]*Mass[bar[Fd],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fd], i2}, {Fd, i1}, {Ah, gE1}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i3}, {Ah, gE2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i4}, {Fd, i2}, {hh, i5}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i4}, {hh, i5}}, C[Fd, hh, bar[Fd]]}}},
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {Fd, i3, 3}, {bar[Fu], i4, 3}, {conj[Hm], i5, 2}},{{6*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[Fd,i3]*Mass[bar[Fu],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fd,i1]*Mass[Fd,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fd,i1]*Mass[bar[Fu],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fd],i2]*Mass[Fd,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fd,i3]*Mass[bar[Fu],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fd], i2}, {Fd, i1}, {Ah, gE1}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i3}, {Ah, gE2}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fu], i4}, {Fd, i2}, {conj[Hm], i5}}, C[Fd, bar[Fu], conj[Hm]]}, {{{bar[Fd], i3}, {Fu, i4}, {Hm, i5}}, C[Fu, Hm, bar[Fd]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {Fe, i3, 3}, {bar[Fe], i4, 3}, {Ah, i5, 3}},{{2*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[Fe,i3]*Mass[bar[Fe],i4],VfFbFbFbFbS,{L, L, L, L}},{4*Mass[Fe,i1]*Mass[Fe,i3],VfFbFFbFS,{L, L, R, L}},{2*Mass[Fe,i1]*Mass[bar[Fe],i4],VfFbFFFbS,{L, L, R, R}},{2*Mass[bar[Fe],i2]*Mass[Fe,i3],VfFFbFbFS,{L, R, L, R}},{4*Mass[Fe,i3]*Mass[bar[Fe],i4],VfFFFbFbS,{L, R, R, R}},{2,VfFFFFS,{L, R, R, L}}},{{{{bar[Fe], i2}, {Fe, i1}, {Ah, gE1}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i3}, {Ah, gE2}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i2}, {Ah, i5}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i4}, {Ah, i5}}, C[Ah, Fe, bar[Fe]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {Fe, i3, 3}, {bar[Fe], i4, 3}, {hh, i5, 3}},{{2*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[Fe,i3]*Mass[bar[Fe],i4],VfFbFbFbFbS,{L, L, L, L}},{4*Mass[Fe,i1]*Mass[Fe,i3],VfFbFFbFS,{L, L, R, L}},{2*Mass[Fe,i1]*Mass[bar[Fe],i4],VfFbFFFbS,{L, L, R, R}},{2*Mass[bar[Fe],i2]*Mass[Fe,i3],VfFFbFbFS,{L, R, L, R}},{4*Mass[Fe,i3]*Mass[bar[Fe],i4],VfFFFbFbS,{L, R, R, R}},{2,VfFFFFS,{L, R, R, L}}},{{{{bar[Fe], i2}, {Fe, i1}, {Ah, gE1}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i3}, {Ah, gE2}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i4}, {Fe, i2}, {hh, i5}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i4}, {hh, i5}}, C[Fe, hh, bar[Fe]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {Fe, i3, 3}, {bar[Fv], i4, 3}, {conj[Hm], i5, 2}},{{2*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[Fe,i3]*Mass[bar[Fv],i4],VfFbFbFbFbS,{L, L, L, L}},{4*Mass[Fe,i1]*Mass[Fe,i3],VfFbFFbFS,{L, L, R, L}},{2*Mass[Fe,i1]*Mass[bar[Fv],i4],VfFbFFFbS,{L, L, R, R}},{2*Mass[bar[Fe],i2]*Mass[Fe,i3],VfFFbFbFS,{L, R, L, R}},{4*Mass[Fe,i3]*Mass[bar[Fv],i4],VfFFFbFbS,{L, R, R, R}},{2,VfFFFFS,{L, R, R, L}}},{{{{bar[Fe], i2}, {Fe, i1}, {Ah, gE1}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i3}, {Ah, gE2}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fv], i4}, {Fe, i2}, {conj[Hm], i5}}, C[Fe, bar[Fv], conj[Hm]]}, {{{bar[Fe], i3}, {Fv, i4}, {Hm, i5}}, C[Fv, Hm, bar[Fe]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {Fu, i3, 3}, {bar[Fu], i4, 3}, {Ah, i5, 3}},{{6*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[Fu,i3]*Mass[bar[Fu],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fu,i1]*Mass[Fu,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fu,i1]*Mass[bar[Fu],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fu],i2]*Mass[Fu,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fu,i3]*Mass[bar[Fu],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fu], i2}, {Fu, i1}, {Ah, gE1}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i3}, {Ah, gE2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i2}, {Ah, i5}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i4}, {Ah, i5}}, C[Ah, Fu, bar[Fu]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {Fu, i3, 3}, {bar[Fu], i4, 3}, {hh, i5, 3}},{{6*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[Fu,i3]*Mass[bar[Fu],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fu,i1]*Mass[Fu,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fu,i1]*Mass[bar[Fu],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fu],i2]*Mass[Fu,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fu,i3]*Mass[bar[Fu],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fu], i2}, {Fu, i1}, {Ah, gE1}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i3}, {Ah, gE2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i4}, {Fu, i2}, {hh, i5}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i4}, {hh, i5}}, C[Fu, hh, bar[Fu]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {Fu, i3, 3}, {bar[Fd], i4, 3}, {Hm, i5, 2}},{{6*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[Fu,i3]*Mass[bar[Fd],i4],VfFbFbFbFbS,{L, L, L, L}},{12*Mass[Fu,i1]*Mass[Fu,i3],VfFbFFbFS,{L, L, R, L}},{6*Mass[Fu,i1]*Mass[bar[Fd],i4],VfFbFFFbS,{L, L, R, R}},{6*Mass[bar[Fu],i2]*Mass[Fu,i3],VfFFbFbFS,{L, R, L, R}},{12*Mass[Fu,i3]*Mass[bar[Fd],i4],VfFFFbFbS,{L, R, R, R}},{6,VfFFFFS,{L, R, R, L}}},{{{{bar[Fu], i2}, {Fu, i1}, {Ah, gE1}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i3}, {Ah, gE2}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fd], i4}, {Fu, i2}, {Hm, i5}}, C[Fu, Hm, bar[Fd]]}, {{{bar[Fu], i3}, {Fd, i4}, {conj[Hm], i5}}, C[Fd, bar[Fu], conj[Hm]]}}}
}},
{GoFFFFV,{
{{{Fd, i1, 3}, {bar[Fd], i2, 3}},{{4,GfFFV,{L, R, 0, 0}},{4*Mass[Fd,i1]*Mass[bar[Fd],i2],GfFbFbV,{L, L, 0, 0}}},{{{{bar[Fd], i2}, {Fd, i1}, {Ah, gE1}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i2}, {Ah, gE2}}, C[Ah, Fd, bar[Fd]]}, {{}, g3}, {{}, g3}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}},{{4,GfFFV,{L, R, 0, 0}},{4*Mass[Fu,i1]*Mass[bar[Fu],i2],GfFbFbV,{L, L, 0, 0}}},{{{{bar[Fu], i2}, {Fu, i1}, {Ah, gE1}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i2}, {Ah, gE2}}, C[Ah, Fu, bar[Fu]]}, {{}, g3}, {{}, g3}}}
}}
}
