(* ----------------------------------------------------------------------------- *) 
(* This model was automatically created by SARAH version4.14.3  *) 
(* SARAH References: arXiv:0806.0538, 0909.2863, 1002.0840, 1207.0906, 1309.7223 *) 
(* (c) Florian Staub, 2013  *) 
(* ----------------------------------------------------------------------------- *) 
(* File created at 12:06 on 29.6.2021  *) 
(* ---------------------------------------------------------------------- *) 
 
 
LoopContributions[PengV2d2nu]={
(* Ah,Fd, Internal:bar[Fd], Propagator: VZ*) 
{{Ah,Fd, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},{mS1 -> M[Ah][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* hh,Fd, Internal:bar[Fd], Propagator: VZ*) 
{{hh,Fd, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},{mS1 -> M[hh][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* VZ,Fd, Internal:bar[Fd], Propagator: VZ*) 
{{VZ,Fd, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},{mV1 -> M[VZ],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* bar[Fu],Hm, Internal:bar[Fd], Propagator: VZ*) 
{{bar[Fu],Hm, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hm][L][i3,i1,i2],coup2R -> Cp[bar[Fd], Fu, Hm][R][i3,i1,i2],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fu][i1],mS1 -> M[Hm][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* bar[Fu],VWm, Internal:bar[Fd], Propagator: VZ*) 
{{bar[Fu],VWm, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWm][L][i3,i1],coup2R -> Cp[bar[Fd], Fu, VWm][R][i3,i1],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fu][i1],mV1 -> M[VWm],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* Fd,Ah, Internal:Fd, Propagator: VZ*) 
{{Fd,Ah, Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1],coup2L -> Cp[bar[Fd], Fd, Ah][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, Ah][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i2],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fd][i1],mS1 -> M[Ah][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}},
(* Fd,hh, Internal:Fd, Propagator: VZ*) 
{{Fd,hh, Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, hh][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i2],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fd][i1],mS1 -> M[hh][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}},
(* Fd,VZ, Internal:Fd, Propagator: VZ*) 
{{Fd,VZ, Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fd][i1],mV1 -> M[VZ],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}},
(* Hm,bar[Fu], Internal:Fd, Propagator: VZ*) 
{{Hm,bar[Fu], Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1],coup2L -> Cp[bar[Fu], Fd, conj[Hm]][L][i2,i3,i1],coup2R -> Cp[bar[Fu], Fd, conj[Hm]][R][i2,i3,i1],coup1L -> Cp[bar[Fd], Fu, Hm][L][gt2,i2,i1],coup1R -> Cp[bar[Fd], Fu, Hm][R][gt2,i2,i1],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},{mS1 -> M[Hm][i1],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}},
(* VWm,bar[Fu], Internal:Fd, Propagator: VZ*) 
{{VWm,bar[Fu], Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1],coup2L -> Cp[bar[Fu], Fd, conj[VWm]][L][i2,i3],coup2R -> Cp[bar[Fu], Fd, conj[VWm]][R][i2,i3],coup1L -> Cp[bar[Fd], Fu, VWm][L][gt2,i2],coup1R -> Cp[bar[Fd], Fu, VWm][R][gt2,i2],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},{mV1 -> M[VWm],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}}
(* Ah,Fd,Fd, Propagator: VZ*) 
{{Ah,Fd,Fd, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup3R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* hh,Fd,Fd, Propagator: VZ*) 
{{hh,Fd,Fd, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup3R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* VZ,Fd,Fd, Propagator: VZ*) 
{{VZ,Fd,Fd, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup3R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fd],hh,Ah, Propagator: VZ*) 
{{bar[Fd],hh,Ah, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZ][i3,i2],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fd],Ah,hh, Propagator: VZ*) 
{{bar[Fd],Ah,hh, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZ][i2,i3],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fd],VZ,hh, Propagator: VZ*) 
{{bar[Fd],VZ,hh, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[hh, VZ, VZ][i3],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fd],hh,VZ, Propagator: VZ*) 
{{bar[Fd],hh,VZ, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup3 -> Cp[hh, VZ, VZ][i2],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],Hm,Hm, Propagator: VZ*) 
{{bar[Fu],Hm,Hm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hm][R][gt2,i1,i3],coup3 -> Cp[Hm, conj[Hm], VZ][i2,i3],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],VWm,Hm, Propagator: VZ*) 
{{bar[Fu],VWm,Hm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, Hm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hm][R][gt2,i1,i3],coup3 -> Cp[conj[Hm], VWm, VZ][i3],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],Hm,VWm, Propagator: VZ*) 
{{bar[Fu],Hm,VWm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, VWm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWm][R][gt2,i1],coup3 -> Cp[Hm, conj[VWm], VZ][i2],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],VWm,VWm, Propagator: VZ*) 
{{bar[Fu],VWm,VWm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWm][R][gt2,i1],coup3 -> Cp[conj[VWm], VWm, VZ],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* conj[Hm],Fu,Fu, Propagator: VZ*) 
{{conj[Hm],Fu,Fu, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hm]][L][i2,gt1,i1],coup1R -> Cp[bar[Fu], Fd, conj[Hm]][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fu, Hm][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fu, Hm][R][gt2,i3,i1],coup3L -> Cp[bar[Fu], Fu, VZ][L][i3,i2],coup3R -> Cp[bar[Fu], Fu, VZ][R][i3,i2],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* conj[VWm],Fu,Fu, Propagator: VZ*) 
{{conj[VWm],Fu,Fu, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWm]][L][i2,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWm]][R][i2,gt1],coup2L -> Cp[bar[Fd], Fu, VWm][L][gt2,i3],coup2R -> Cp[bar[Fd], Fu, VWm][R][gt2,i3],coup3L -> Cp[bar[Fu], Fu, VZ][L][i3,i2],coup3R -> Cp[bar[Fu], Fu, VZ][R][i3,i2],coup4L -> Cp[bar[Fv], Fv, VZ][L][gt4,gt3],coup4R -> Cp[bar[Fv], Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* Hm,Fe,Fe, Propagator: VZ*) 
{{Hm,Fe,Fe, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hm][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fe, conj[Hm]][L][gt4,i3,i1],coup2R -> Cp[bar[Fv], Fe, conj[Hm]][R][gt4,i3,i1],coup3L -> Cp[bar[Fe], Fe, VZ][L][i3,i2],coup3R -> Cp[bar[Fe], Fe, VZ][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* VWm,Fe,Fe, Propagator: VZ*) 
{{VWm,Fe,Fe, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWm][R][i2,gt3],coup2L -> Cp[bar[Fv], Fe, conj[VWm]][L][gt4,i3],coup2R -> Cp[bar[Fv], Fe, conj[VWm]][R][gt4,i3],coup3L -> Cp[bar[Fe], Fe, VZ][L][i3,i2],coup3R -> Cp[bar[Fe], Fe, VZ][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[Hm],conj[Hm], Propagator: VZ*) 
{{bar[Fe],conj[Hm],conj[Hm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hm][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fe, conj[Hm]][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fe, conj[Hm]][R][gt4,i1,i3],coup3 -> Cp[Hm, conj[Hm], VZ][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[VWm],conj[Hm], Propagator: VZ*) 
{{bar[Fe],conj[VWm],conj[Hm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWm][R][i1,gt3],coup2L -> Cp[bar[Fv], Fe, conj[Hm]][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fe, conj[Hm]][R][gt4,i1,i3],coup3 -> Cp[Hm, conj[VWm], VZ][i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[Hm],conj[VWm], Propagator: VZ*) 
{{bar[Fe],conj[Hm],conj[VWm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hm][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fe, conj[VWm]][L][gt4,i1],coup2R -> Cp[bar[Fv], Fe, conj[VWm]][R][gt4,i1],coup3 -> Cp[conj[Hm], VWm, VZ][i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[VWm],conj[VWm], Propagator: VZ*) 
{{bar[Fe],conj[VWm],conj[VWm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWm][R][i1,gt3],coup2L -> Cp[bar[Fv], Fe, conj[VWm]][L][gt4,i1],coup2R -> Cp[bar[Fv], Fe, conj[VWm]][R][gt4,i1],coup3 -> Cp[conj[VWm], VWm, VZ],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],}
};