{{{conj[Hm], Fe, Cp[bar[UFv[{gO1}]], conj[Hm[{gI1}]], Fe[{gI2}]], FFS, 1, 1}, 
  {conj[VWm], Fe, Cp[bar[UFv[{gO1}]], conj[VWm], Fe[{gI2}]], FFV, 1, 1}, 
  {VZ, Fv, Cp[bar[UFv[{gO1}]], VZ, Fv[{gI2}]], FFV, 1, 1}}, 
 {{bar[Fd], Fd, Cp[VG, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 1/2, 1/2}, 
  {bar[Fu], Fu, Cp[VG, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 1/2, 1/2}, 
  {bar[gG], gG, Cp[VG, bar[gG], gG], GGV, 3, 1/2}, 
  {VG, VG, Cp[VG, VG, VG], VVV, 3, 1/4}, {VG, VG, Cp[VG, VG, VG, VG], VVVV, 
   1, 1/2}}, {{bar[Fd], Fd, Cp[VP, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fe], Fe, Cp[VP, bar[Fe[{gI1}]], Fe[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fu], Fu, Cp[VP, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 3, 1/2}, 
  {bar[gWm], gWm, Cp[VP, bar[gWm], gWm], GGV, 1, 1/2}, 
  {bar[gWmC], gWmC, Cp[VP, bar[gWmC], gWmC], GGV, 1, 1/2}, 
  {conj[Hm], Hm, Cp[VP, conj[Hm[{gI1}]], Hm[{gI2}]], SSV, 1, 1/2}, 
  {conj[VWm], Hm, Cp[VP, conj[VWm], Hm[{gI2}]], SVV, 1, 1}, 
  {conj[VWm], VWm, Cp[VP, conj[VWm], VWm], VVV, 1, 1/2}, 
  {conj[Hm], Hm, Cp[VP, VP, conj[Hm[{gI1}]], Hm[{gI1}]], SSVV, 1, 1}, 
  {conj[VWm], VWm, Cp[VP, VP, conj[VWm], VWm], VVVV, 1, 1}}, 
 {{hh, Ah, Cp[VZ, hh[{gI1}], Ah[{gI2}]], SSV, 1, 1/2}, 
  {bar[Fd], Fd, Cp[VZ, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fe], Fe, Cp[VZ, bar[Fe[{gI1}]], Fe[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fu], Fu, Cp[VZ, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fv], Fv, Cp[VZ, bar[Fv[{gI1}]], Fv[{gI2}]], FFV, 1, 1/2}, 
  {bar[gWm], gWm, Cp[VZ, bar[gWm], gWm], GGV, 1, 1/2}, 
  {bar[gWmC], gWmC, Cp[VZ, bar[gWmC], gWmC], GGV, 1, 1/2}, 
  {VZ, hh, Cp[VZ, VZ, hh[{gI2}]], SVV, 1, 1/2}, 
  {conj[Hm], Hm, Cp[VZ, conj[Hm[{gI1}]], Hm[{gI2}]], SSV, 1, 1/2}, 
  {conj[VWm], Hm, Cp[VZ, conj[VWm], Hm[{gI2}]], SVV, 1, 1}, 
  {conj[VWm], VWm, Cp[VZ, conj[VWm], VWm], VVV, 1, 1/2}, 
  {Ah, Ah, Cp[VZ, VZ, Ah[{gI1}], Ah[{gI1}]], SSVV, 1, 1/2}, 
  {hh, hh, Cp[VZ, VZ, hh[{gI1}], hh[{gI1}]], SSVV, 1, 1/2}, 
  {conj[Hm], Hm, Cp[VZ, VZ, conj[Hm[{gI1}]], Hm[{gI1}]], SSVV, 1, 1}, 
  {conj[VWm], VWm, Cp[VZ, VZ, conj[VWm], VWm], VVVV, 1, 1}}, 
 {{Hm, Ah, Cp[conj[VWm], Hm[{gI1}], Ah[{gI2}]], SSV, 1, 1}, 
  {bar[Fu], Fd, Cp[conj[VWm], bar[Fu[{gI1}]], Fd[{gI2}]], FFV, 3, 1}, 
  {bar[Fv], Fe, Cp[conj[VWm], bar[Fv[{gI1}]], Fe[{gI2}]], FFV, 1, 1}, 
  {bar[gWmC], gP, Cp[conj[VWm], bar[gWmC], gP], GGV, 1, 1}, 
  {bar[gP], gWm, Cp[conj[VWm], bar[gP], gWm], GGV, 1, 1}, 
  {bar[gZ], gWm, Cp[conj[VWm], bar[gZ], gWm], GGV, 1, 1}, 
  {bar[gWmC], gZ, Cp[conj[VWm], bar[gWmC], gZ], GGV, 1, 1}, 
  {Hm, hh, Cp[conj[VWm], Hm[{gI1}], hh[{gI2}]], SSV, 1, 1}, 
  {VWm, hh, Cp[conj[VWm], VWm, hh[{gI2}]], SVV, 1, 1}, 
  {VP, Hm, Cp[conj[VWm], VP, Hm[{gI2}]], SVV, 1, 1}, 
  {VZ, Hm, Cp[conj[VWm], VZ, Hm[{gI2}]], SVV, 1, 1}, 
  {VWm, VP, Cp[conj[VWm], VWm, VP], VVV, 1, 1}, 
  {VZ, VWm, Cp[conj[VWm], VZ, VWm], VVV, 1, 1}, 
  {Ah, Ah, Cp[VWm, conj[VWm], Ah[{gI1}], Ah[{gI1}]], SSVV, 1, 1/2}, 
  {hh, hh, Cp[VWm, conj[VWm], hh[{gI1}], hh[{gI1}]], SSVV, 1, 1/2}, 
  {conj[Hm], Hm, Cp[VWm, conj[VWm], conj[Hm[{gI1}]], Hm[{gI1}]], SSVV, 1, 1}, 
  {VP, VP, Cp[VWm, conj[VWm], VP, VP], VVVV, 1, 1/2}, 
  {conj[VWm], VWm, Cp[VWm, conj[VWm], conj[VWm], VWm], VVVV, 1, 1}, 
  {VZ, VZ, Cp[VWm, conj[VWm], VZ, VZ], VVVV, 1, 1/2}}}
