{{{bar[Fd[{gt1, ct1}]], Fd[{gt2, ct2}], VG[{ct3, lt3}]}, 
  {(-1/2*I)*g3*Delta[gt1, gt2]*Lam[ct3, ct1, ct2], 
   LorentzProduct[gamma[lt3], PL]}, 
  {(-1/2*I)*g3*Delta[gt1, gt2]*Lam[ct3, ct1, ct2], 
   LorentzProduct[gamma[lt3], PR]}}, 
 {{bar[Fd[{gt1, ct1}]], Fd[{gt2, ct2}], VP[{lt3}]}, 
  {(-1/6*I)*Delta[ct1, ct2]*Delta[gt1, gt2]*(g1*Cos[ThetaW] - 
     3*g2*Sin[ThetaW]), LorentzProduct[gamma[lt3], PL]}, 
  {(I/3)*g1*Cos[ThetaW]*Delta[ct1, ct2]*Delta[gt1, gt2], 
   LorentzProduct[gamma[lt3], PR]}}, 
 {{bar[Fd[{gt1, ct1}]], Fd[{gt2, ct2}], VZ[{lt3}]}, 
  {(I/6)*Delta[ct1, ct2]*Delta[gt1, gt2]*(3*g2*Cos[ThetaW] + g1*Sin[ThetaW]), 
   LorentzProduct[gamma[lt3], PL]}, 
  {(-1/3*I)*g1*Delta[ct1, ct2]*Delta[gt1, gt2]*Sin[ThetaW], 
   LorentzProduct[gamma[lt3], PR]}}, 
 {{bar[Fu[{gt1, ct1}]], Fd[{gt2, ct2}], conj[VWm[{lt3}]]}, 
  {((-I)*g2*Delta[ct1, ct2]*sum[j1, 1, 3, conj[Vd[gt2, j1]]*Vu[gt1, j1]])/
    Sqrt[2], LorentzProduct[gamma[lt3], PL]}, {0, PR}}, 
 {{bar[Fe[{gt1}]], Fe[{gt2}], VP[{lt3}]}, 
  {(I/2)*Delta[gt1, gt2]*(g1*Cos[ThetaW] + g2*Sin[ThetaW]), 
   LorentzProduct[gamma[lt3], PL]}, {I*g1*Cos[ThetaW]*Delta[gt1, gt2], 
   LorentzProduct[gamma[lt3], PR]}}, {{bar[Fe[{gt1}]], Fe[{gt2}], VZ[{lt3}]}, 
  {(I/2)*Delta[gt1, gt2]*(g2*Cos[ThetaW] - g1*Sin[ThetaW]), 
   LorentzProduct[gamma[lt3], PL]}, {(-I)*g1*Delta[gt1, gt2]*Sin[ThetaW], 
   LorentzProduct[gamma[lt3], PR]}}, 
 {{bar[Fv[{gt1}]], Fe[{gt2}], conj[VWm[{lt3}]]}, 
  {((-I)*g2*conj[Ve[gt2, gt1]]*ThetaStep[gt1, 3])/Sqrt[2], 
   LorentzProduct[gamma[lt3], PL]}, {0, PR}}, 
 {{bar[Fu[{gt1, ct1}]], Fu[{gt2, ct2}], VG[{ct3, lt3}]}, 
  {(-1/2*I)*g3*Delta[gt1, gt2]*Lam[ct3, ct1, ct2], 
   LorentzProduct[gamma[lt3], PL]}, 
  {(-1/2*I)*g3*Delta[gt1, gt2]*Lam[ct3, ct1, ct2], 
   LorentzProduct[gamma[lt3], PR]}}, 
 {{bar[Fu[{gt1, ct1}]], Fu[{gt2, ct2}], VP[{lt3}]}, 
  {(-1/6*I)*Delta[ct1, ct2]*Delta[gt1, gt2]*(g1*Cos[ThetaW] + 
     3*g2*Sin[ThetaW]), LorentzProduct[gamma[lt3], PL]}, 
  {((-2*I)/3)*g1*Cos[ThetaW]*Delta[ct1, ct2]*Delta[gt1, gt2], 
   LorentzProduct[gamma[lt3], PR]}}, 
 {{bar[Fd[{gt1, ct1}]], Fu[{gt2, ct2}], VWm[{lt3}]}, 
  {((-I)*g2*Delta[ct1, ct2]*sum[j1, 1, 3, conj[Vu[gt2, j1]]*Vd[gt1, j1]])/
    Sqrt[2], LorentzProduct[gamma[lt3], PL]}, {0, PR}}, 
 {{bar[Fu[{gt1, ct1}]], Fu[{gt2, ct2}], VZ[{lt3}]}, 
  {(-1/6*I)*Delta[ct1, ct2]*Delta[gt1, gt2]*(3*g2*Cos[ThetaW] - 
     g1*Sin[ThetaW]), LorentzProduct[gamma[lt3], PL]}, 
  {((2*I)/3)*g1*Delta[ct1, ct2]*Delta[gt1, gt2]*Sin[ThetaW], 
   LorentzProduct[gamma[lt3], PR]}}, 
 {{bar[Fe[{gt1}]], Fv[{gt2}], VWm[{lt3}]}, 
  {((-I)*g2*ThetaStep[gt2, 3]*Ve[gt1, gt2])/Sqrt[2], 
   LorentzProduct[gamma[lt3], PL]}, {0, PR}}, 
 {{bar[Fv[{gt1}]], Fv[{gt2}], VZ[{lt3}]}, 
  {(-1/2*I)*Delta[gt1, gt2]*(g2*Cos[ThetaW] + g1*Sin[ThetaW]), 
   LorentzProduct[gamma[lt3], PL]}, {0, PR}}}
