{{{bar[Fd], Fd, Cp[Uhh[{gO1}], bar[Fd[{gI1}]], Fd[{gI2}]], FFS, 3, 1/2}, 
  {bar[Fe], Fe, Cp[Uhh[{gO1}], bar[Fe[{gI1}]], Fe[{gI2}]], FFS, 1, 1/2}, 
  {bar[Fu], Fu, Cp[Uhh[{gO1}], bar[Fu[{gI1}]], Fu[{gI2}]], FFS, 3, 1/2}, 
  {bar[gWm], gWm, Cp[Uhh[{gO1}], bar[gWm], gWm], GGS, 1, 1/2}, 
  {bar[gWmC], gWmC, Cp[Uhh[{gO1}], bar[gWmC], gWmC], GGS, 1, 1/2}, 
  {bar[gZ], gZ, Cp[Uhh[{gO1}], bar[gZ], gZ], GGS, 1, 1/2}, 
  {hh, hh, Cp[Uhh[{gO1}], hh[{gI1}], hh[{gI2}]], SSS, 1, 1/4}, 
  {VZ, hh, Cp[Uhh[{gO1}], VZ, hh[{gI2}]], SSV, 1, 1/2}, 
  {conj[Hm], Hm, Cp[Uhh[{gO1}], conj[Hm[{gI1}]], Hm[{gI2}]], SSS, 1, 1/2}, 
  {conj[VWm], Hm, Cp[Uhh[{gO1}], conj[VWm], Hm[{gI2}]], SSV, 1, 1}, 
  {conj[VWm], VWm, Cp[Uhh[{gO1}], conj[VWm], VWm], SVV, 1, 1/2}, 
  {VZ, VZ, Cp[Uhh[{gO1}], VZ, VZ], SVV, 1, 1/4}, 
  {hh, hh, Cp[Uhh[{gO1}], Uhh[{gO1}], hh[{gI1}], hh[{gI1}]], SSSS, 1, 1/2}, 
  {conj[Hm], Hm, Cp[Uhh[{gO1}], Uhh[{gO1}], conj[Hm[{gI1}]], Hm[{gI1}]], 
   SSSS, 1, 1}, {conj[VWm], VWm, Cp[Uhh[{gO1}], Uhh[{gO1}], conj[VWm], VWm], 
   SSVV, 1, 1}, {VZ, VZ, Cp[Uhh[{gO1}], Uhh[{gO1}], VZ, VZ], SSVV, 1, 1/2}}, 
 {{bar[Fu], Fd, Cp[conj[UHm[{gO1}]], bar[Fu[{gI1}]], Fd[{gI2}]], FFS, 3, 1}, 
  {bar[Fv], Fe, Cp[conj[UHm[{gO1}]], bar[Fv[{gI1}]], Fe[{gI2}]], FFS, 1, 1}, 
  {bar[gZ], gWm, Cp[conj[UHm[{gO1}]], bar[gZ], gWm], GGS, 1, 1}, 
  {bar[gWmC], gZ, Cp[conj[UHm[{gO1}]], bar[gWmC], gZ], GGS, 1, 1}, 
  {Hm, hh, Cp[conj[UHm[{gO1}]], Hm[{gI1}], hh[{gI2}]], SSS, 1, 1}, 
  {VWm, hh, Cp[conj[UHm[{gO1}]], VWm, hh[{gI2}]], SSV, 1, 1}, 
  {VP, Hm, Cp[conj[UHm[{gO1}]], VP, Hm[{gI2}]], SSV, 1, 1}, 
  {VZ, Hm, Cp[conj[UHm[{gO1}]], VZ, Hm[{gI2}]], SSV, 1, 1}, 
  {VWm, VP, Cp[conj[UHm[{gO1}]], VWm, VP], SVV, 1, 1}, 
  {VZ, VWm, Cp[conj[UHm[{gO1}]], VZ, VWm], SVV, 1, 1}, 
  {hh, hh, Cp[UHm[{gO1}], conj[UHm[{gO1}]], hh[{gI1}], hh[{gI1}]], SSSS, 1, 
   1/2}, {conj[Hm], Hm, Cp[UHm[{gO1}], conj[UHm[{gO1}]], conj[Hm[{gI1}]], 
    Hm[{gI1}]], SSSS, 1, 1}, {VP, VP, Cp[UHm[{gO1}], conj[UHm[{gO1}]], VP, 
    VP], SSVV, 1, 1/2}, {conj[VWm], VWm, Cp[UHm[{gO1}], conj[UHm[{gO1}]], 
    conj[VWm], VWm], SSVV, 1, 1}, {VZ, VZ, Cp[UHm[{gO1}], conj[UHm[{gO1}]], 
    VZ, VZ], SSVV, 1, 1/2}}, 
 {{hh, Fd, Cp[bar[UFd[{gO1}]], hh[{gI1}], Fd[{gI2}]], FFS, 1, 1}, 
  {VG, Fd, Cp[bar[UFd[{gO1}]], VG, Fd[{gI2}]], FFV, 4/3, 1}, 
  {VP, Fd, Cp[bar[UFd[{gO1}]], VP, Fd[{gI2}]], FFV, 1, 1}, 
  {VZ, Fd, Cp[bar[UFd[{gO1}]], VZ, Fd[{gI2}]], FFV, 1, 1}, 
  {Hm, Fu, Cp[bar[UFd[{gO1}]], Hm[{gI1}], Fu[{gI2}]], FFS, 1, 1}, 
  {VWm, Fu, Cp[bar[UFd[{gO1}]], VWm, Fu[{gI2}]], FFV, 1, 1}}, 
 {{conj[Hm], Fd, Cp[bar[UFu[{gO1}]], conj[Hm[{gI1}]], Fd[{gI2}]], FFS, 1, 1}, 
  {conj[VWm], Fd, Cp[bar[UFu[{gO1}]], conj[VWm], Fd[{gI2}]], FFV, 1, 1}, 
  {hh, Fu, Cp[bar[UFu[{gO1}]], hh[{gI1}], Fu[{gI2}]], FFS, 1, 1}, 
  {VG, Fu, Cp[bar[UFu[{gO1}]], VG, Fu[{gI2}]], FFV, 4/3, 1}, 
  {VP, Fu, Cp[bar[UFu[{gO1}]], VP, Fu[{gI2}]], FFV, 1, 1}, 
  {VZ, Fu, Cp[bar[UFu[{gO1}]], VZ, Fu[{gI2}]], FFV, 1, 1}}, 
 {{hh, Fe, Cp[bar[UFe[{gO1}]], hh[{gI1}], Fe[{gI2}]], FFS, 1, 1}, 
  {VP, Fe, Cp[bar[UFe[{gO1}]], VP, Fe[{gI2}]], FFV, 1, 1}, 
  {VZ, Fe, Cp[bar[UFe[{gO1}]], VZ, Fe[{gI2}]], FFV, 1, 1}, 
  {Hm, Fv, Cp[bar[UFe[{gO1}]], Hm[{gI1}], Fv[{gI2}]], FFS, 1, 1}, 
  {VWm, Fv, Cp[bar[UFe[{gO1}]], VWm, Fv[{gI2}]], FFV, 1, 1}}}
